"""Generate HL7 v2 ACK messages from a source message + validation outcome."""
from __future__ import annotations

from datetime import datetime, timezone

from app.services.parser import parse_message


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")


def _field_value(seg: dict, pos: int) -> str:
    for f in seg["fields"]:
        if f["position"] == pos:
            if not f["repetitions"]:
                return ""
            rep = f["repetitions"][0]
            return "^".join(
                "&".join(s["value"] for s in c["subcomponents"])
                for c in rep["components"]
            )
    return ""


def generate_ack(original_text: str, validation: dict | None = None) -> str:
    """Return an HL7 v2 ACK message.

    Ack code:
      AA — accept (no ERROR results)
      AE — error (validation produced ERROR results)
      AR — reject (message couldn't be parsed / no MSH)
    """
    try:
        parsed = parse_message(original_text)
    except Exception:
        # Can't build a meaningful ACK without MSH-10. Return a minimal rejection.
        return "\r".join([
            f"MSH|^~\\&|||||{_now()}||ACK^A01^ACK|ACK{_now()}|P|2.5",
            "MSA|AR||Message could not be parsed; no original control ID available.",
        ])

    msh = parsed["segments"][0]
    sending_app = _field_value(msh, 3)
    sending_fac = _field_value(msh, 4)
    receiving_app = _field_value(msh, 5)
    receiving_fac = _field_value(msh, 6)
    control_id = _field_value(msh, 10) or "UNKNOWN"
    version = _field_value(msh, 12) or "2.5"
    processing_id = _field_value(msh, 11) or "P"

    if validation and not validation.get("is_valid", True):
        ack_code = "AE"
    else:
        ack_code = "AA"

    ack_control_id = f"ACK{_now()}"

    msh_out = (
        f"MSH|^~\\&|{receiving_app or 'HL7INSPECTOR'}|{receiving_fac}|"
        f"{sending_app}|{sending_fac}|{_now()}||ACK^A01^ACK|{ack_control_id}|"
        f"{processing_id}|{version}"
    )
    msa_out = f"MSA|{ack_code}|{control_id}|Generated by HL7 Inspector (local acknowledgement only)"

    return "\r".join([msh_out, msa_out])